### ISSUE TITLE
Plugin breaks Pages displaying

### ISSUE THREAD

**Issue by athlan** [athlan/wordpress-custom-fields-permalink-plugin#17]
When custom permalink structure is set up, then pages cannot be displayed.

**Comment by athlan** [comment]
Because there is same rewrite rule for posts and pages it could be difficult to fix.

Creating field default values is recommended for now:

https://github.com/athlan/wordpress-custom-fields-permalink-plugin/wiki/FAQ#how-to-generate-calculated-dynamic-custom-post-meta-keys-and-values

**Comment by eimpacteric** [comment]
Bummer...this is a deal break

Nice plugin otherwise +1

**Comment by qingyangge** [comment]
hello,it means that do not use the plugin,and just copy the code in function.php?

**Comment by qingyangge** [comment]
page is very important in wordpress,if the page url bug can not be fixed,your plugin can not be need for many wordpresser!

**Comment by athlan** [comment]
The fix is available under PR https://github.com/athlan/wordpress-custom-fields-permalink-plugin/pull/34. It will cause one consequence. Let's discuss about it under Pull request.

**Comment by athlan** [comment]
Fixed in 1.5.0
