### ISSUE TITLE
Static pages rewrite does not work

### ISSUE THREAD

**Issue by medimapa** [athlan/wordpress-custom-fields-permalink-plugin#2]
Hello Athlan:

I've installed your plugin and I'm having some problem.

I'm using WP Job Manager inside wordpress and when I install the plugin and activate it, my theme stops working and static home page is turn into blog archive. This seems to happen with all static pages.

Is there a way just to use custom fields only inside custom post types?

Greetings

**Comment by athlan** [comment]
Howdy @medimapa.

Plugin registers listeners for all routes. If you want to work with these routes in custom pot types, as it is mentioned in documentation, you have to install addiotional Custom Post Type Permalinks
 https://wordpress.org/plugins/custom-post-type-permalinks/. This plugin enables you to set another rules per custom post type.

To solve your issue:
Please go to the "Settings -> Permalink" configuration page and simply click "Save". This will reload all rewrite rules in your Wordpress.
