### ISSUE TITLE
Need custom fields sanitized

### ISSUE THREAD

**Issue by montreyw** [athlan/wordpress-custom-fields-permalink-plugin#3]
Hey,
I'm using your plugin alongside https://wordpress.org/plugins/custom-post-type-permalinks/. The problem is, if one of my custom field has special characters or has spaces or capitalization, your plugin tries to still use the field, as is, in the URL. What i would like to do is have your plugin "sanitize" the custom field data before it makes the URL. An example would be if i had a field that had "Athlan Piotr Pelczar" i would like it to come out as "athlan-piotr-pelczar". It looks like this fuction https://codex.wordpress.org/Function_Reference/sanitize_title or a similar one should resolve the issue but i'm not sure where to insert it in your code. Can you help?

**Comment by athlan** [comment]
Related with #1.

**Comment by athlan** [comment]
Closed in dd901fd.
