### ISSUE TITLE
Got some php warnings while using the plugin

### ISSUE THREAD

**Issue by cosminchiriac** [athlan/wordpress-custom-fields-permalink-plugin#30]
Hi,

I created a few custom fields using the Toolset Type plugin. Then I used your plugin to include the values of 2 custom fields in the permalink. After I did this, I got the warnings that you may see bellow. Please let me know if you need more details.

Warning: Invalid argument supplied for foreach() in /home/mediapi1/public_html/honda-eu.ro/wp-content/plugins/custom-fields-permalink-redux/includes/class-wp-post-meta.php on line 38

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/mediapi1/public_html/honda-eu.ro/wp-content/plugins/custom-fields-permalink-redux/includes/class-wp-request-processor.php on line 103

Warning: Cannot modify header information - headers already sent by (output started at /home/mediapi1/public_html/honda-eu.ro/wp-content/plugins/custom-fields-permalink-redux/includes/class-wp-post-meta.php:38) in /home/mediapi1/public_html/honda-eu.ro/wp-includes/pluggable.php on line 1219

Thanks,
Cosmin

**Comment by athlan** [comment]
Hello @cosminchiriac .

Can you please provide:
1. Whether you implemented filter custom `wpcfp_get_post_metadata` or not.
2. What i the output for `var_dump(get_post_meta( $post->ID ))` for the post you are trying to make permalink. You can dump it on the mainpage inside a post loop.
3. What is your permalink structure settings.
4. (Optional, 2nd point will reveal it). Do you have `get_{$meta_type}_metadata` filter implemented by some 3rd party plugin ([reference](https://developer.wordpress.org/reference/hooks/get_meta_type_metadata/))?

Cheers,
Piotr

**Comment by athlan** [comment]
@cosminchiriac Just a reminder.
