### ISSUE TITLE
Hello,I use the plugin,but the page permalink is something wrong!

### ISSUE THREAD

**Issue by qingyangge** [athlan/wordpress-custom-fields-permalink-plugin#32]
Hello,I use the plugin,but the page permalink is something wrong!
I open any page url links,and it open but the content is wrong.not the page content,when I close the plugin,then visit the page url ,which showing right content.
I guess there must some bug with your plugin in page url!
Hoping you can fix it!And the plugin is good plugin,I love it very much!

**Comment by athlan** [comment]
https://github.com/athlan/wordpress-custom-fields-permalink-plugin/issues/33 has been created. Please subscribe for updates if needed.
