### ISSUE TITLE
Does not work on hierarchical custom post type children

### ISSUE THREAD

**Issue by bkmacdaddy** [athlan/wordpress-custom-fields-permalink-plugin#35]
Plugin works great for hierarchical custom post type parents but on children the field name is blank (example.com/post-type//child-post). This could also/instead be an issue with the Custom Post Type Permalinks plugin - not sure. Just letting you know the unique use case I have that may not yet have come up with users of this plugin.

**Comment by bkmacdaddy** [comment]
Further testing leads me to believe this is actually an issue with the Custom Post Type Permalinks plugin. Apologies for posting prematurely.

**Comment by athlan** [comment]
Thanks a lot for contact.
If you found plugin useful, please vote for it: https://wordpress.org/support/plugin/custom-fields-permalink-redux/reviews/
