### ISSUE TITLE
Error on post page

### ISSUE THREAD

**Issue by anthonyqkiernan** [athlan/wordpress-custom-fields-permalink-plugin#36]
Following on from here
https://wordpress.org/support/topic/error-on-post-page-2/#post-10776009

1. Which version of plugin are you using?
Custom Fields Permalink 2 Version 1.4.0

2. Do you have specified some hook filter on wpcfp_get_post_metadata?
No.  This is pretty much an OTB installation.  I've imported content from the live site, then installed the above plugin.  Then seen the issue 

3. Which plugin are you using?
See question 1?

4. Are you referring to non-existing post to generate permalink maybe?
No, I can see the post fine on the previous set url e.g. http://localhost:8888/sample-post/

5. Are you able to provide full reproducible scenario?
I changed the settings to below (not a fieldname with a hyphen in it). 
http://localhost:8888/%postname%-%field_myFieldName% 
This fails.  If I change it to
http://localhost:8888/%postname%/%field_myFieldName% 
It works

**Comment by athlan** [comment]
Hello @anthonyqkiernan . I cannot reproduce your scenario with putting `-` in field name and then replacing it by `_`. It always works for me.

Could you please give end to end reproducible scenario?

Before you start, please go to permalink page and click Save.

**Comment by athlan** [comment]
No response for a long time. Closing.
