### ISSUE TITLE
When the article is made private, the following error is displayed.

### ISSUE THREAD

**Issue by MingPaint** [athlan/wordpress-custom-fields-permalink-plugin#38]
When the article is made private, the following error is displayed.
Warning: Invalid argument supplied for foreach() in /var/www/html/web/wp/wp-content/plugins/custom-fields-permalink-redux/includes/class-wp-post-meta.php on line 38

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /var/www/html/web/wp/wp-content/plugins/custom-fields-permalink-redux/includes/class-wp-post-meta.php on line 59

**Comment by athlan** [comment]
Hello,

Thank you for raising an issue. I can reproduce it.

Picking it up.

**Comment by athlan** [comment]
@MingPaint . Fix is done and ready to release:
https://github.com/athlan/wordpress-custom-fields-permalink-plugin/pull/39

Please review the code before releasing next version if you want.

**Comment by athlan** [comment]
Fixed in 1.5.0
