### ISSUE TITLE
%field_fieldname% doesnt work

### ISSUE THREAD

**Issue by Sasha111ua** [athlan/wordpress-custom-fields-permalink-plugin#44]
I created a custom post type called article using Toolset plugin. Added a custom field called ezpublishid to it. Wanted to use ezpublishid value as a part of permalink, but it is always empty. Same happens to default post type.
![image](https://user-images.githubusercontent.com/8628097/55792887-dfb6d500-5ac1-11e9-9df5-d1e26315e76b.png)
![image](https://user-images.githubusercontent.com/8628097/55792947-0a089280-5ac2-11e9-93f2-e11ff2f93076.png)

**Comment by athlan** [comment]
Hello,

please send the output for following code when accessing this post making sure that field exists:
```
var_dump($post->ID, get_post_meta($post->ID)));
```

**Comment by Sasha111ua** [comment]
Thanks, var_dump showed that property id is wpcf-ezpublishid
