### ISSUE TITLE
default value for unset 

### ISSUE THREAD

**Issue by HongPong** [athlan/wordpress-custom-fields-permalink-plugin#45]
Hi, I have a situation they threw at us at the last second before launch 🙄 

we have posts (regular post type) which have an optional "Relationship" ACF field value. I would like to insert the name of that relationship post (its title in lowercase I suppose), but have some kind of default value in effect if that field is not set. (because I assume it will give two slashes with nothing between them, if there is no value here).

I didn't see anything in the documentation or code about fallback values if the ACF field is not set. Thank you!

**Comment by athlan** [comment]
Hello,

I hope Wiki article fits your use case.
https://github.com/athlan/wordpress-custom-fields-permalink-plugin/wiki/FAQ#how-to-generate-missing-custom-post-meta-keys-and-values

**Comment by HongPong** [comment]
thanks for the quick reply! I will give it a try. Frankly I could simply set this to be a required field and that would be acceptable in this case.

**Comment by athlan** [comment]
If plugin works for you and you appreciate support :beers: , leave a review:
https://wordpress.org/support/plugin/custom-fields-permalink-redux/reviews/
