### ISSUE TITLE
Special Characters ignored

### ISSUE THREAD

**Issue by coresinceeightyfour** [athlan/wordpress-custom-fields-permalink-plugin#6]
Great plugin, but it seems to ignore special characters (?%&) in the custom field. I would need those to attach deeplink parameters. Would appreciate an update :)

**Comment by coresinceeightyfour** [comment]
Ah sorry, solved it for me by removing         $value = sanitize_title($value);

**Comment by athlan** [comment]
Can you give me an example of use case when you don't want display sanitized values? Remember, that they are not url-safe, but I can imagine such situation when sanitization does make a problem.

Can you give a proposal of configuration such situation in URL scheme? such as: `/my/posts/%field_some_name[sanitization=false]%/`
