### ISSUE TITLE
Quick fix for where a meta tag is duplicate

### ISSUE THREAD

**Issue by arnonzamir** [athlan/wordpress-custom-fields-permalink-plugin#7]
Great plugin. Slick and functional. 

I had a website with some post that have duplicate meta tags with similar keys. Strange and unwanted, but it was there.
It may be useful for someone so here's my quick-fix: 

```php
public static function linkRewriteFieldsExtract($post, $fieldName) {
        $postMeta = get_post_meta($post->ID);
        if(!isset($postMeta[$fieldName]))
            return '';	

	//deal with duplicate keys by taking the value of the first
        if (is_array($postMeta[$fieldName])) {
			$value =  $postMeta[$fieldName][0];	
		} else {
			$value = implode('', $postMeta[$fieldName]);
        }
        $value = sanitize_title($value);
        return $value;
    }
```

**Comment by athlan** [comment]
Hello,

Thank you for the contribution. Indeed, it is an another case I didn’t considered. Soon I will review code and make some tests and release a new version.

**Comment by athlan** [comment]
@arnonzamir the fix is proposed. Please look at the test suite with expected behavior:
https://github.com/athlan/wordpress-custom-fields-permalink-plugin/pull/9

**Comment by athlan** [comment]
Fixed.
